colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: The Internet Marketing Mom
layout_spectrum: 0.7486083146650344
typography_spectrum: 0.41072788392193615
color:
  brandStrength: 0.5024312401656061
  lightness: 0.8564432950224727
  saturation: 0.5720862264279276
  rhythmicContrast: 0.8834466584958136
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f77549d3-b241-46e2-b6b4-bad84f40503e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f77549d3-b241-46e2-b6b4-bad84f40503e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'http://internetmarketing.mom'
github: true
title: ''
description: 'A Motivational, Practical Site For Hard-Working Moms'
